version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./panel:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ctrlpanel
      DB_USERNAME: ctrluser
      DB_PASSWORD: maycolpass

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maycolroot
      MYSQL_DATABASE: ctrlpanel
      MYSQL_USER: ctrluser
      MYSQL_PASSWORD: maycolpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
